print("WELCOME TO THE STRING & ESCAPE CHARACTER PROJECT")
print("-" * 40)
Name = input("Enter Your Name: ")
Age = float(input("Enter your age: "))

print("\nHello Everyone.")
print(f"{Name}, How Are You?")
print(f"{Name} {Age}")
print(f"{Name}\t{Age}")
print("new\\old")
print(f"this is python\"s class")
print(f'this is python\'s class')
print(f"he says, \"we are learning python\"")
print(f"PROJECT COMPLETED SUCCESSFULLY ✔")
